-- The data the mcp_sample solution filters by tenant, for running the sample by hand.
--
-- Run this against the database behind example_data, then open mcp_sample in the developer and
-- point an MCP client at /servoy-service/mcp/mcp_sample with one of the demo tokens.
--
-- salesTools_listMyItems uses QBSelect and comes back filtered: three rows for alice (acme), two
-- for bob (globex). salesTools_countRows asks with a SQL string and comes back with all five - a
-- tenant filter applies to queries Servoy builds, not to raw SQL.
--
-- Created rather than dropped and recreated: the table may already be there, carrying the tenant
-- flag in its .dbi, and dropping it would take that with it. Emptying it is enough.

create table if not exists mcp_tenant_demo (
	item_id integer generated by default as identity primary key,
	tenant_name varchar(50),
	item_name varchar(100));

delete from mcp_tenant_demo;

insert into mcp_tenant_demo (tenant_name, item_name) values ('acme', 'Acme anvil');
insert into mcp_tenant_demo (tenant_name, item_name) values ('acme', 'Acme rocket');
insert into mcp_tenant_demo (tenant_name, item_name) values ('acme', 'Acme rope');
insert into mcp_tenant_demo (tenant_name, item_name) values ('globex', 'Globex gadget');
insert into mcp_tenant_demo (tenant_name, item_name) values ('globex', 'Globex widget');
