/*
 This file belongs to the Servoy development and deployment environment, Copyright (C) 1997-2010 Servoy BV

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation; either version 3 of the License, or (at your option) any
 later version.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License along
 with this program; if not, see http://www.gnu.org/licenses or write to the Free
 Software Foundation,Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301
 */
package com.servoy.j2db.query;

import java.util.concurrent.atomic.AtomicLong;

import com.servoy.j2db.util.Immutable;
import com.servoy.j2db.util.serialize.ReplacedObject;
import com.servoy.j2db.util.visitor.IVisitor;

/**
 * Table class in the query structure. The alias is generated by this class in the constructor.
 * 
 * @author rgansevles
 * 
 */
public final class QueryTable implements IQueryElement, Immutable
{
	private final String name;
	private final String alias;
	private final boolean needsQuoting;
	private transient String catalogName;
	private transient String schemaName;
	private final transient boolean generatedAlias;
	private transient boolean isComplete;

	private static AtomicLong aliasCounter = new AtomicLong(0);

	/**
	 * @param name table name as used in sql, may be quoted
	 */
	public QueryTable(String name, String catalogName, String schemaName)
	{
		this(name, catalogName, schemaName, true);
	}

	/**
	 * @param name table name as used in sql, may be quoted
	 */
	public QueryTable(String name, String catalogName, String schemaName, boolean needsQuoting)
	{
		this(name, catalogName, schemaName, null, needsQuoting);
	}

	public QueryTable(String name, String catalogName, String schemaName, String alias)
	{
		this(name, catalogName, schemaName, alias, true);
	}

	public QueryTable(String name, String catalogName, String schemaName, String alias, boolean needsQuoting)
	{
		this.name = name;
		this.catalogName = catalogName;
		this.schemaName = schemaName;
		this.generatedAlias = alias == null;
		this.alias = this.generatedAlias ? generateAlias(name) : alias;
		this.needsQuoting = needsQuoting;
		this.isComplete = true;
	}

	/**
	 * @param name
	 */
	private static String generateAlias(String name)
	{
		// Skip anything but letters and digits
		StringBuffer aliasBuf = new StringBuffer();
		char[] chars = name.toCharArray();
		for (char element : chars)
		{
			if (Character.isLetterOrDigit(element))
			{
				aliasBuf.append(element);
			}
		}

		// generate next counter
		long n = aliasCounter.incrementAndGet() & 0x7fffffffffffffffL;

		if (aliasBuf.length() == 0) // weird table name
		{
			return "T_" + n; //$NON-NLS-1$
		}

		aliasBuf.append(n);
		return aliasBuf.toString();
	}

	public String getName()
	{
		return name;
	}

	public String getCatalogName()
	{
		return this.catalogName;
	}

	public String getSchemaName()
	{
		return this.schemaName;
	}

	public String getAlias()
	{
		return alias;
	}

	public boolean isAliasGenerated()
	{
		return generatedAlias;
	}

	public boolean needsQuoting()
	{
		return needsQuoting;
	}

	public boolean isComplete()
	{
		return isComplete;
	}

	public Object shallowClone() throws CloneNotSupportedException
	{
		return super.clone();
	}

	public void acceptVisitor(IVisitor visitor)
	{
	}


	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((this.alias == null) ? 0 : this.alias.hashCode());
		result = prime * result + ((this.catalogName == null) ? 0 : this.catalogName.hashCode());
		result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
		result = prime * result + ((this.schemaName == null) ? 0 : this.schemaName.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (this == obj) return true;
		if (obj == null) return false;
		if (getClass() != obj.getClass()) return false;
		final QueryTable other = (QueryTable)obj;
		if (this.alias == null)
		{
			if (other.alias != null) return false;
		}
		else if (!this.alias.equals(other.alias)) return false;
		if (this.catalogName == null)
		{
			if (other.catalogName != null) return false;
		}
		else if (!this.catalogName.equals(other.catalogName)) return false;
		if (this.name == null)
		{
			if (other.name != null) return false;
		}
		else if (!this.name.equals(other.name)) return false;
		if (this.schemaName == null)
		{
			if (other.schemaName != null) return false;
		}
		else if (!this.schemaName.equals(other.schemaName)) return false;
		return true;
	}

	@Override
	public String toString()
	{
		StringBuffer sb = new StringBuffer();
		if (catalogName != null)
		{
			sb.append(catalogName).append(':');
		}
		if (schemaName != null)
		{
			sb.append(schemaName).append(':');
		}
		sb.append(name);
		if (alias != null)
		{
			sb.append('#').append(alias);
		}
		return sb.toString();
	}

	///////// serialization ////////////////

	public Object writeReplace()
	{
		// just need to serialize the name, the alias can be regenerated.
		// Note: this only works if the query object was packed before serialization!
		// catalogName and schemaName will be regenerated on the server
		return new ReplacedObject(AbstractBaseQuery.QUERY_SERIALIZE_DOMAIN, getClass(), generatedAlias ? (needsQuoting ? (Object)name : new Object[] { name })
			: new Object[] { name, alias, Boolean.valueOf(needsQuoting) });
	}

	public QueryTable(ReplacedObject s)
	{
		Object o = s.getObject();
		if (o instanceof Object[])
		{
			Object[] members = (Object[])o;
			int i = 0;
			name = (String)members[i++];
			if (members.length == 1)
			{
				// [name], needsQuoting = false
				needsQuoting = false;
				alias = generateAlias(name);
				generatedAlias = true;
			}
			else
			{
				// [name, alias, needsQuoting]
				alias = (String)members[i++];
				needsQuoting = ((Boolean)members[i++]).booleanValue();
				generatedAlias = false;
			}
		}
		else
		{ // name
			name = (String)o;
			needsQuoting = true;
			alias = generateAlias(name);
			generatedAlias = true;
		}

		// catalogName and schemaName will be regenerated on the server
		isComplete = false;
		catalogName = null;
		schemaName = null;
	}

	/**
	 * Update the fields that have not been set in serialization
	 */
	public void update(String catalogName, String schemaName)
	{
		this.catalogName = catalogName;
		this.schemaName = schemaName;
		isComplete = true;
	}
}
