source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               lib/mcp-core-2.0.1.jar,\
               lib/reactor-core-3.8.7.jar,\
               lib/reactive-streams-1.0.4.jar
